mumbai testnet deployment settings
kumodao/borrowprot pull request #125
Opened 2022-05-16 05:41 UTC by asimpk

tested mumbai testnet deployment using frontend sdk

2022-05-17 07:27 UTC, udosson requested changes
@asimpk - thanks for the PR. Could you (1) please remove all not used artifacts related to the Ethereum mainnet and its testnets, please? And (2) could you please synchronize with @arthurka-o regarding the deployment? Thank you!

2022-05-17 07:27 UTC, udosson commented on packages/lib-ethers/src/EthersKumoConnection.ts
>  import rinkeby from "../deployments/rinkeby.json";
Could you remove the old artifacts from Liquity? We only need Mumbai and Polygon

2022-05-17 07:27 UTC, udosson commented on packages/dev-frontend/src/hooks/KumoContext.tsx
> +const supportedNetworks = ["homestead", "kovan", "rinkeby", "ropsten", "goerli", "mumbai"];
Could you remove the old artifacts from Liquity? We only need Mumbai and Polygon

2022-05-17 14:25 UTC, asimpk commented
> @asimpk could you change the base branch to `kumodao:30-ll-deploy-the-protocol-to-mumbai-polygon-testnet`, please?

@udosson yeah sure thanks, PR will be ready for merge after my session with Arthur

2022-05-18 09:45 UTC, udosson commented
> > @asimpk could you change the base branch to `kumodao:30-ll-deploy-the-protocol-to-mumbai-polygon-testnet`, please?
> 
> @udosson yeah sure thanks, PR will be ready for merge after my session with @arthurka-o

perfect, @asimpk. Please, take care of the commits that are part of your PR. I recommend to have only 1 commit with only the changes needed rather than 62 in total. Thank you

2022-05-18 10:16 UTC, asimpk commented
> > > @asimpk could you change the base branch to `kumodao:30-ll-deploy-the-protocol-to-mumbai-polygon-testnet`, please?
> > 
> > 
> > @udosson yeah sure thanks, PR will be ready for merge after my session with @arthurka-o
> 
> perfect, @asimpk. Please, take care of the commits that are part of your PR. I recommend to have only 1 commit with only the changes needed rather than 62 in total. Thank you



> > > @asimpk could you change the base branch to `kumodao:30-ll-deploy-the-protocol-to-mumbai-polygon-testnet`, please?
> > 
> > 
> > @udosson yeah sure thanks, PR will be ready for merge after my session with @arthurka-o
> 
> perfect, @asimpk. Please, take care of the commits that are part of your PR. I recommend to have only 1 commit with only the changes needed rather than 62 in total. Thank you

hi @udosson tbh I don't know why I'm getting list of all these commits , these are all old, I make only 3 commits first one two days ago and then yesterday, It seems some branch issues or maybe something else

2022-05-18 14:27 UTC, udosson commented
How I would proceed:
```git checkout main
# if you haven't added the upstream repository, do: git remote add upstream https://github.com/kumodao/borrowprot.git
git fetch upstream
git merge upstream/main```

Now, your local `main` branch of your fork is updated with `main` from kumodao.

Next, create a new branch from `main` by running `git checkout -b NAME_OF_YOUR_BRANCH` and `cherry-pick` your commit or do the changes again.

Let me know if I can support you further

2022-05-27 10:22 UTC, udosson commented
Merged similar PR #133

2022-05-27 10:22 UTC, closed without merging