Feat test networks remove
kumodao/borrowprot pull request #133
Opened 2022-05-24 20:57 UTC by asimpk

2022-05-26 11:12 UTC, udosson requested changes
Thanks @asimpk - Just a few small changes ;)

2022-05-26 11:12 UTC, udosson commented on packages/lib-ethers/src/EthersKumoConnection.ts
>  import devOrNull from "../deployments/dev.json";
please add 
`import devOrNull from "../deployments/mumbai.json";`

2022-05-26 11:12 UTC, udosson commented on packages/lib-ethers/hardhat.config.ts
> +      accounts: ['ff126760c1b50be914c632a2cfbcbbfc569e21d07008c92c861e8977f0c01544'],
Remove private key and use `.env` file instead

2022-05-26 11:12 UTC, udosson commented on packages/lib-ethers/hardhat.config.ts
>    mainnet: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
Please update `wethAddresses` for Polygon and Mumbai network

2022-05-26 11:12 UTC, udosson commented on packages/lib-ethers/hardhat.config.ts
> +  mumbai: {
update chainlink and tellor addresses, please.
This needs to be updated for Mumbai and Polygon PoS

2022-05-26 14:20 UTC, asimpk commented on packages/lib-ethers/hardhat.config.ts
> +  mumbai: {
Please verify are these addresses are correct?
` mainnet: {
    chainlink: "0xb33D8A4e62236eA91F3a8fD7ab15A95B9B7eEc7D",
    tellor: "0xe3322702bedaaed36cddab233360b939775ae5f1"
  },
  mumbai: {
    chainlink: "0x58bbdbfb6fca3129b91f0dbe372098123b38b5e9",
    tellor: "0x3477EB82263dabb59AC0CAcE47a61292f28A2eA7" // Core
  },`

2022-05-26 15:17 UTC, udosson commented on packages/lib-ethers/hardhat.config.ts
> +  mumbai: {
@asimpk 
the Tellor address for mainnet is https://polygonscan.com/address/0xfd45ae72e81adaaf01cc61c8bce016b7060dd537#code

You can get the addresses for the chainlink data feeds for ETH/USD here:
Polygon Mainnet: https://docs.chain.link/docs/matic-addresses/#Polygon%20Mainnet
Mumbai Testnet: https://docs.chain.link/docs/matic-addresses/#Mumbai%20Testnet

2022-05-27 07:38 UTC, udosson approved these changes
Looks perfect - @asimpk. Thank you!
Let's merge this PR in our call today

2022-05-27 10:10 UTC, merged