Upgrade solidity to 0.8.11
kumodao/borrowprot pull request #23
Opened 2022-04-01 20:23 UTC by wollooo

and fix all the failing test that occured

2022-04-02 11:10 UTC, udosson requested changes
@wollooo thanks for the PR. Could you merge all commits into one commit after making the changes, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/BorrowerOperations.sol
> +    bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/BorrowerOperations.sol
> +        isInitialized = true;
Could you set this as comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/CollSurplusPool.sol
> +    bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/DefaultPool.sol
> +	bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/HintHelpers.sol
> +                + (troveManager.getPendingLUSDDebtReward(currentTroveuser));
Can your revert this back to `.add()`, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/LPRewards/Unipool.sol
> +    bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/LQTY/LQTYStaking.sol
> +    bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/LQTY/LockupContract.sol
> +	bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/LQTY/LockupContractFactory.sol
> +	bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/PriceFeed.sol
> +	bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/SortedTroves.sol
> +	bool public isInitialized;
Could you set this as a comment, please?

2022-04-02 11:10 UTC, udosson commented on packages/contracts/contracts/StabilityPool.sol
> +    bool public isInitialized;
Could you set this as a comment, please?

2022-04-04 14:06 UTC, wollooo commented
All done, please see [#24](https://github.com/kumodao/borrowprot/pull/24)

2022-04-05 07:09 UTC, udosson commented
@wollooo can this PR be closed?

2022-04-06 15:03 UTC, closed without merging