Switch to kusd
kumodao/borrowprot pull request #66
Opened 2022-04-08 18:38 UTC by wollooo

see https://github.com/kumodao/borrowprot/issues/34

2022-04-08 18:43 UTC, wollooo commented
I switched LUSD to KUSD in the entrie rroject. Is this a problem @udosson ?

2022-04-11 19:44 UTC, wollooo commented
I messed up to create a new branch for the switch to KUMO. So in this branch you can find the switch from LQTY to KUMO.

2022-04-12 15:47 UTC, udosson commented
I'm still reviewing but I see some files still named `*liquity*` like `docs/sdk/lib-base.liquitystorebasestate.totalstakedunitokens.md`
Could we change them to `*kumo*` as well?

2022-04-14 14:54 UTC, udosson requested changes
@wollooo This PR is awesome! Your regex skills rock!
Could you please make the small adjustments found as comments and in our discord chat?
Also, it would be great if you could change all `*liquity*`, `*lqty*`, and `*lusd*` filenames to the corresponding `kumo` names.
I'm looking forward to merging your PR.

2022-04-19 16:01 UTC, wollooo commented on docs/sdk/lib-base.liquidationdetails.md
> +|  [KUSDGasCompensation](./lib-base.liquidationdetails.kusdgascompensation.md) | [Decimal](./lib-base.decimal.md) | Amount of KUSD paid to the liquidator as gas compensation. |
yes it is automatically generated

2022-04-19 16:13 UTC, wollooo commented on docs/sdk/lib-base.liquitystorebasestate.kusdbalance.md
> +## LiquityStoreBaseState.kusdBalance property
Everything looks right to me. I think git has mapped the changes incorrectly. There is always one file for KUSD and one for KUMO. See here:

- [kumobalance.md](https://github.com/wollooo/borrowprot/blob/switch-to-kusd/docs/sdk/lib-base.liquitystorebasestate.kumobalance.md)
- [kusdbalance.md](https://github.com/wollooo/borrowprot/blob/switch-to-kusd/docs/sdk/lib-base.liquitystorebasestate.kusdbalance.md)

2022-04-19 16:14 UTC, wollooo commented on docs/sdk/lib-base.liquitystorebasestate.kusdbalance.md
> +User's KUSD token balance.
https://github.com/kumodao/borrowprot/pull/66#discussion_r853255253

2022-04-19 16:14 UTC, wollooo commented on docs/sdk/lib-base.liquitystorebasestate.kusdbalance.md
> +kusdBalance: Decimal;
https://github.com/kumodao/borrowprot/pull/66#discussion_r853255253

2022-04-19 16:45 UTC, wollooo commented on docs/sdk/lib-ethers.ethersliquity.getkumobalance.md
> +[Home](./index.md) &gt; [@liquity/lib-ethers](./lib-ethers.md) &gt; [EthersLiquity](./lib-ethers.ethersliquity.md) &gt; [getKUMOBalance](./lib-ethers.ethersliquity.getkumobalance.md)
similar to https://github.com/kumodao/borrowprot/pull/66#discussion_r853255253

2022-04-23 08:34 UTC, udosson approved these changes
@wollooo thank you so much for this amazing contribution. Kudos!!!

2022-04-23 08:34 UTC, merged